export const POSTE_LIST_REQUEST = 'POSTE_LIST_REQUEST';
export const POSTE_LIST_SUCCESS = 'POSTE_LIST_SUCCESS';
export const POSTE_LIST_FAIL = 'POSTE_LIST_FAIL';

export const POSTE_DETAILS_REQUEST = 'POSTE_DETAILS_REQUEST';
export const POSTE_DETAILS_SUCCESS = 'POSTE_DETAILS_SUCCESS';
export const POSTE_DETAILS_FAIL = 'POSTE_DETAILS_FAIL';

export const POSTE_CREATE_REQUEST = 'POSTE_CREATE_REQUEST';
export const POSTE_CREATE_SUCCESS = 'POSTE_CREATE_SUCCESS';
export const POSTE_CREATE_FAIL = 'POSTE_CREATE_FAIL';
export const POSTE_CREATE_RESET = 'POSTE_CREATE_RESET';

export const POSTE_REVIEW_CREATE_REQUEST = 'POSTE_REVIEW_CREATE_REQUEST';
export const POSTE_REVIEW_CREATE_SUCCESS = 'POSTE_REVIEW_CREATE_SUCCESS';
export const POSTE_REVIEW_CREATE_FAIL = 'POSTE_REVIEW_CREATE_FAIL';
export const POSTE_REVIEW_CREATE_RESET = 'POSTE_REVIEW_CREATE_RESET';

export const POSTE_UPDATE_REQUEST = 'POSTE_UPDATE_REQUEST';
export const POSTE_UPDATE_SUCCESS = 'POSTE_UPDATE_SUCCESS';
export const POSTE_UPDATE_FAIL = 'POSTE_UPDATE_FAIL';
export const POSTE_UPDATE_RESET = 'POSTE_UPDATE_RESET';

export const POSTE_DELETE_REQUEST = 'POSTE_DELETE_REQUEST';
export const POSTE_DELETE_SUCCESS = 'POSTE_DELETE_SUCCESS';
export const POSTE_DELETE_FAIL = 'POSTE_DELETE_FAIL';
export const POSTE_DELETE_RESET = 'POSTE_DELETE_RESET';

